[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/research/*"
  to = "https://ryuwryyy.github.io/niwa-sorairo/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
